/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./TrackApplication.module.css";

const NavigationItem = ({ text }) => <li className={styles.navItem}>{text}</li>;

export default NavigationItem;
