/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavigationItem from "./NavigationItem";
import styles from "./TrackApplication.module.css";

const navigationItems = [
  "About",
  "Scholarships",
  "Students",
  "Applications",
  "Contact",
];

const NavigationList = () => (
  <ul className={styles.navList}>
    {navigationItems.map((item, index) => (
      <NavigationItem key={index} text={item} />
    ))}
  </ul>
);

export default NavigationList;
