/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavigationList from "./NavigationList";
import styles from "./TrackApplication.module.css";

const TrackApplication = () => {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <div className={styles.headerSpacer} />
        <NavigationList />
      </header>
      <h1 className={styles.title}>Track your application</h1>
      <main className={styles.formContainer}>
        <form className={styles.formLayout}>
          <div className={styles.inputColumn}>
            <div className={styles.inputField}>
              <label htmlFor="applicationId" className={styles.label}>
                Enter application id
              </label>
              <input
                id="applicationId"
                className={styles.input}
                type="text"
                aria-label="Enter application id"
              />
            </div>
          </div>
          <div className={styles.buttonColumn}>
            <button type="submit" className={styles.trackButton}>
              Track
            </button>
          </div>
        </form>
      </main>
    </div>
  );
};

export default TrackApplication;
