/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./NavigationPill.module.css";

const NavigationPill = ({ children }) => {
  return <div className={styles.navigationPill}>{children}</div>;
};

export default NavigationPill;
