/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ScholarshipApplication.module.css";
import Button from "./Button";
import NavigationPill from "./NavigationPill";
import { Link } from "react-router-dom";

const ScholarshipApplication = () => {
  const navItems = [
    "About",
    "Scholarships",
    "Students",
    "Applications",
    "Contact",
  ];

  return (
    <div className={styles.scholarshipApplication}>
      <header className={styles.header}>
        <nav className={styles.navigation}>
          {navItems.map((item, index) => (
            <NavigationPill key={index}>{item}</NavigationPill>
          ))}
        </nav>
        <div className={styles.authButtons}>
        <Link to='/login' ><Button variant="secondary">Sign in</Button></Link>
          <Link to='/register'><Button variant="primary">Register</Button></Link>
        </div>
      </header>
      <main className={styles.heroSection}>
        <section className={styles.heroContent}>
          <h1 className={styles.heroTitle}>
            Ease your scholarship application
          </h1>
          <p className={styles.heroSubtitle}>
            Apply for the scholarship now and claim quick Start your
            registration
          </p>
        </section>
        <div className={styles.heroButtons}>
        <Link to='/login' >  <Button variant="secondary">Login</Button></Link>
          <Button variant="primary">Register</Button>
        </div>
      </main>
    </div>
  );
};

export default ScholarshipApplication;
