/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./RegistrationPage.module.css";

const AuthButton = ({ label, isRegister }) => (
  <button
    className={`${styles.authButton} ${
      isRegister ? styles.registerButton : styles.signInButton
    }`}
  >
    {label}
  </button>
);

export default AuthButton;
