/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./RegistrationPage.module.css";

const InputField = ({ label, type, id }) => (
  <div className={styles.inputField}>
    <label htmlFor={id} className={styles["visually-hidden"]}>
      {label}
    </label>
    <input
      type={type}
      id={id}
      className={styles.input}
      placeholder={label}
      aria-label={label}
    />
  </div>
);

export default InputField;
