/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./RegistrationPage.module.css";

const NavigationItem = ({ label }) => (
  <div className={styles.navigationItem}>{label}</div>
);

export default NavigationItem;
