/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LoginPage.module.css";
import NavItem from "./NavItem";
import AuthButton from "./AuthButton";
import InputField from "./InputField";

const navItems = [
  { text: "About", href: "#" },
  { text: "Scholarships", href: "#" },
  { text: "Track Application", href: "/track" },
  { text: "Applications", href: "#" },
  { text: "Contact", href: "#" },
];

function LoginPage() {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <div className={styles.spacer} />
        <nav className={styles.navList}>
          {navItems.map((item, index) => (
            <NavItem key={index} text={item.text} href={item.href} />
          ))}
        </nav>
        <div className={styles.authContainer}>
          <AuthButton text="Sign in" />
          <AuthButton text="Register" isRegister />
        </div>
      </header>
      <main className={styles.mainContent}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6fe3afba8c84a0998cd4417b9348e73837a62626c11c0e08aba3615dee5d4d7e?placeholderIfAbsent=true&apiKey=ee31ec960f4c431fa5d7b4a441b2ce47"
          className={styles.loginImage}
          alt="Login illustration"
        />
        <form className={styles.loginForm}>
          <h1 className={styles.loginTitle}>Login</h1>
          <InputField label="Username" type="text" />
          <InputField label="Password" type="password" isPassword />
          <a href='/apply'><button type="button"  className={styles.loginButton}>
            Login
          </button></a>
        </form>
      </main>
    </div>
  );
}

export default LoginPage;
