/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LoginPage.module.css";

function NavItem({ text, href }) {
    return (
      <a href={href} className={styles.navItem}>
        {text}
      </a>
    );
  }

export default NavItem;
