/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ScholarshipDialog.module.css";

const Button = ({ children, isPrimary, ...props }) => (
  <button
    className={isPrimary ? styles.primaryButton : styles.secondaryButton}
    {...props}
  >
    {children}
  </button>
);

const ScholarshipDialog = () => {
  return (
    <section
      className={styles.dialog}
      role="dialog"
      aria-labelledby="dialogTitle"
    >
      <div className={styles.content}>
        <h2 id="dialogTitle" className={styles.message}>
          Scholarship applied successfully
        </h2>
      </div>
      <div className={styles.actions}>
        <Button>cancel</Button>
        <Button isPrimary>ok</Button>
      </div>
    </section>
  );
};

export default ScholarshipDialog;
