/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ApplicationForm.module.css";

const NavigationPill = ({ label }) => {
  return <div className={styles.navigationPill}>{label}</div>;
};

export default NavigationPill;
