/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./DialogComponent.module.css";

function Button({ children, variant, className }) {
  return (
    <button className={`${styles[`${variant}Button`]} ${className}`}>
      <div className={styles.buttonContent}>{children}</div>
    </button>
  );
}

export default Button;
