/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./DialogComponent.module.css";
import Button from "./Button";

function DialogComponent() {
  return (
    <section
      className={styles.dialog}
      role="dialog"
      aria-labelledby="dialogTitle"
    >
      <div className={styles.content}>
        <h2 id="dialogTitle" className={styles.title}>
          Application is under processing
        </h2>
      </div>
      <div className={styles.actions}>
        <div className={styles.actionButtons}>
          <Button variant="secondary" className={styles.secondaryButton}>
            Cancel
          </Button>
          <Button variant="primary" className={styles.primaryButton}>
            Ok
          </Button>
        </div>
      </div>
    </section>
  );
}

export default DialogComponent;
